#!/usr/bin/env python
# Author Michele Mattioni
# Fri Apr  9 11:35:29 BST 2010
import sys
import os
sys.path.append(os.path.realpath(os.path.join(os.path.abspath(__file__), "../..")))

if __name__ == '__main__':
    from neuronvisio.command_line import main_neuronvisio
    main_neuronvisio()
    