#!/usr/bin/env python
# Author Michele Mattioni
# Tue Feb 14 15:47:08 GMT 2012

"""Updates the ModelDB.xml in the current location"""

import sys
import os
sys.path.append(os.path.realpath(os.path.join(os.path.abspath(__file__), "../..")))


if __name__ == '__main__':

    from neuronvisio.command_line import main_model_updater
    main_model_updater()
    